// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS63DX0gcqtj1pOfksOyDrXLVgr4Ae774',
    appId: '1:419624144502:web:ef56f73bc53b527a869957',
    messagingSenderId: '419624144502',
    projectId: 'gbook-8c360',
    authDomain: 'gbook-8c360.firebaseapp.com',
    storageBucket: 'gbook-8c360.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MDxotnEsglkQWbzsp_czWa-2mxKIXd0',
    appId: '1:419624144502:android:5a1a4bf5b14fb93c869957',
    messagingSenderId: '419624144502',
    projectId: 'gbook-8c360',
    storageBucket: 'gbook-8c360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-LgvSa6Z598XRAacwNTYInQ9RtGVlTTc',
    appId: '1:419624144502:ios:636b4c31dd983a3d869957',
    messagingSenderId: '419624144502',
    projectId: 'gbook-8c360',
    storageBucket: 'gbook-8c360.firebasestorage.app',
    iosBundleId: 'com.gbook.gbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-LgvSa6Z598XRAacwNTYInQ9RtGVlTTc',
    appId: '1:419624144502:ios:636b4c31dd983a3d869957',
    messagingSenderId: '419624144502',
    projectId: 'gbook-8c360',
    storageBucket: 'gbook-8c360.firebasestorage.app',
    iosBundleId: 'com.gbook.gbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV9KJeh7Z1UK6f7McCiAGehXy6sjeJG60',
    appId: '1:419624144502:web:d2af4238e6d505da869957',
    messagingSenderId: '419624144502',
    projectId: 'gbook-8c360',
    authDomain: 'gbook-8c360.firebaseapp.com',
    storageBucket: 'gbook-8c360.firebasestorage.app',
  );
}
